name: Telegram Bot Check-in

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 每天 00:00 UTC (北京时间上午 8:00) 运行
    # 您可以根据需要修改这里的 cron 表达式
    - cron: '0 0 * * *'

jobs:
  check-in:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # 使用一个较新的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run check-in script
      env:
        # 从 GitHub Secrets 中读取凭据并设置为环境变量
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
      run: python main.py 