name: Telegram Bot Check-in

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 在 UTC 时间 16:01 运行 (北京时间次日 00:01)
    # cron 格式: 分钟(0-59) 小时(0-23) 日(1-31) 月(1-12) 星期(0-6)
    - cron: '1 16 * * *'

jobs:
  check-in:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # 使用一个较新的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run check-in script
      env:
        # 从 GitHub Secrets 中读取凭据并设置为环境变量
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
      run: python main.py 